version: '3.9'

services: 
  nhlApi:
    container_name: ${CONTAINER_NAME}
    image: ${CONTAINER_NAME}
    environment: 
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    build: 
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports: 
      - ${CONTAINER_PORT}:${CONTAINER_PORT}
    command: npm run start:dev
    networks: 
      - webnet
networks:
  webnet:
volumes:
  node_modules: